services:
  postgis:
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      POSTGRES_DB: yelp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "4444:5432"

  qdrant:
    image: qdrant/qdrant:v1.7.3
    container_name: qdrant
    ports:
      - "6333:6333"